server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: clientConsumer
          uri: lb://client-consumer
          #uri: http://localhost:8065
          predicates:
            - Path=/clientConsumer/**
          filters:
            - AddRequestHeader=user-request-header, custom-user-request-header
            - AddResponseHeader=user-response-header, custom-user-response-header
            - LogFilter= Mensaje, hola Julieta!
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
